export type FullOrder = {
  idx: string;
  vid: string;
  total: number;
  percentage: number;
  simple: number;
  weighted_simple: number;
  pagerank: number;
  elo: number;
  entropy: number;
  title_ja: string;
  title_en: string;
  title_zh: string;
  alias: string;
  search: string;
  c_votecount: number;
  c_rating: number;
  c_average: number;
  rank: number;
};